# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcae1b4bb816d3ca6c81b0ef6e94f9c86b1672d30cc804a7fe8cba7f2b3d0ec5ced9bc62a6245505f2f8b347e5d5330edac9277f0fd8799b870ace9ce4d3e684

test:
  secret_key_base: b998226f08d3e30bde77917bc4708ea06b3a947afe1955f8692767747f6fc80d7334f79f4905e1b0472c0e79a35ca465bf0bd10ae791dd4b8f5ec28ddb94204e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
